swagger: "2.0"
info:
  description: "Solutions Data API is the single entrypoint to access aggregated and processed data from Swarm Perception Boxes®."
  version: "1.0.0"
  title: "Solutions Data API"
host: "swarm-data-center.swarm-analytics.com"
basePath: "/v1"
schemes:
- "https"
paths:
  /parkingdata/spaces/{spaceUUID}:
    get:
      tags:
      - Parking
      summary: "Get Parking Space"
      produces:
      - "application/json"
      parameters:
      - name: "spaceUUID"
        in: "path"
        description: "UUID of the parking space"
        required: true
        type: "string"
        format: "uuid"
      responses:
        "200":
          description: "successful operation"
          examples:
            application/json:
              {
                "node": {
                  "id": "test",
                  "name": "test"
                },
                "regionOfInterestEvent": {
                  "objects": [
                    {
                      "class": "person"
                    }
                  ],
                  "roiId": "69031920-6239-471e-a3d7-f241b7753fd0",
                  "roiName": "R1",
                  "state": "occupied",
                  "timestamp": "2020-01-02T14:59:27.85136Z",
                  "triggerType": "time"
                }
              }
  /trafficdata/flows:
    get:
      tags:
      - Traffic Monitoring
      summary: "Get Traffic Flows from Entry Zone to Exit Zone"
      parameters:
      - name: "entryZone"
        in: "query"
        description: "UIID of the entry zone"
        type: "string"
        format: "uuid"
      - name: "exitZone"
        in: "query"
        description: "UIID of the exit zone"
        type: "string"
        format: "uuid"
      responses:
        "200":
          description: "successful operation"
          examples:
            application/json:
               {
                 "version":"1.0",
                 "node":{
                    "id":"b8ade223-e847-4741-a405-7f62c0403aa2",
                    "name":"test"
                 },
                 "trafficEvent":{
                    "classification":"car",
                    "entry":{
                       "zone":{
                          "zoneId":"56317209-9B83-43A6-A63E-58C9191A7869",
                          "name":"entryZoneName"
                       },
                       "timestamp":"2019-12-29T10:31:14.373202Z"
                    },
                    "exit":{
                       "zone":{
                          "zoneId":"c28ed4e8-bf1b-4c2e-9938-aeb28687f7aa",
                          "name":"exitZoneName"
                       },
                       "timestamp":"2019-12-29T10:31:20.373202Z"
                    },
                    "movementPath":[
                       {
                          "timestamp":"2019-12-29T10:31:14.373202Z",
                          "h":554.192138671875,
                          "w":766.527587890625,
                          "x":0.0,
                          "y":525.807861328125
                       },
                       {
                          "timestamp":"2019-12-29T10:31:20.373202Z",
                          "h":757.2371215820313,
                          "w":1013.7042236328125,
                          "x":131.88348388671875,
                          "y":157.8472137451172
                       }
                    ]
                 }
              }
  
